### PR TITLE
Text formatting for python script

### PR DESCRIPTION
**Pull request by kant**
Plus some minor proposals.

### CODE REVIEW

**Comment by maheshwarishikha** [comment]
Suggestions accepted wherever appropriate. Thanks.

**Comment by stevemar** [comment]
@maheshwarishikha use the merge option to add the changes, not close

**Comment by maheshwarishikha** [comment]
@stevemart , sure Steve. As I changed Readme content so all suggested changes were not applicable hence made the recommended changes and close.

**Comment by stevemar** [comment]
ok

**Pull request closed without merging**
